export const AUTHENTICATE_USER = 'AUTHENTICATE USER';
export const CREATED_USER_SUCCESS = 'CREATED_USER_SUCCESS';
export const LOADING_SUCCESS = 'LOADING_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const EMAIL_OR_PASSWORD_ERROR = 'EMAIL_OR_PASSWORD_ERROR';
